spring:
    datasource:
        url: jdbc:postgresql://db_postgresql:5432/test
        username: postgres
        password: password
    jpa:
        hibernate:
            ddl-auto: create-drop
            show-sql: true
    batch:
        initialize-schema: always
server:
    error:
        include-message: always
