spring:
    datasource:
        url: jdbc:postgresql://192.168.99.100:5432/test
        username: postgres
        password: password
    jpa:
        hibernate:
            ddl-auto: create-drop
            show-sql: true
    batch:
        initialize-schema: always
